### PR TITLE
Fix assembly analysis applet failures for less than 1x coverage genomes.

### PR DESCRIPTION
**Pull request by dpark01**
The assembly analysis applet fails whenever mean_coverage_depth is less than 1x coverage. See DNAnexus support ticket 2633. Suggested fix by @mckinsel .

### CODE REVIEW

**Comment by mlin** [comment]
@dpark01 @tomkinsc sorry, the test failures did not relate to this patch but were left over from the upgrade to the v1.15.3 docker image, which I neglected to notice at the time. In particular the number of aligned bases in the output BAM for the test sample SRR1553554 decreased slightly from 590,547 to 577,417. Unrelated to this change which I'll release shortly, but thought I should mention in in case it's not expected.

**Comment by dpark01** [comment]
Sounds great, thanks for that fix @mlin. I don't feel right merging on your repo (even though it looks like I have permission to), can you go ahead and merge the PR?

**Comment by mlin** [comment]
@dpark01 okay I updated the pipelines in the featured project

**Comment by dpark01** [comment]
thanks!

**Pull request merged**
